---
- name: "check weather rsa files exist"
  stat: path={{home_path}}/.ssh/{{ item.src }}
  with_items:
    - { src: id_rsa.pub }
    - { src: id_rsa }
  register: rsa
  delegate_to: localhost
  ignore_errors: True

- name: "install sshpass by apt"
  apt:
    name: sshpass
    state: present
  when: ansible_os_family == 'Debian'
  ignore_errors: True

- name: "create rsa"
  shell: yes y |ssh-keygen -b 2048 -t rsa -f {{home_path}}/.ssh/id_rsa -q -N ""
  delegate_to: localhost
  when: (rsa.results[0].stat.exists == false) or (rsa.results[1].stat.exists == false)

- name: "install ssh key"
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '{{home_path}}/.ssh/id_rsa.pub') }}"

- name: "add repo"
  apt_repository:
    repo: ppa:longsleep/golang-backports
  become: true
  become_method: sudo

- name: "install golang"
  apt:
    name: golang-go
    update_cache: yes
  become: true
  become_method: sudo
