#!/bin/bash

#helm upgrade
#upgrade a release

#need kafkaui-0.0.9.tgz in current path, generated by package-kafkaui.sh

#./upgrade-tgz-kafkaui.sh
 #Release "kafkaui" has been upgraded. Happy Helming!
 #NAME: kafkaui
 #LAST DEPLOYED: Thu Apr 20 16:12:34 2023
 #NAMESPACE: kafkaui
 #STATUS: deployed
 #REVISION: 10
 #TEST SUITE: None
 #NOTES:
 #1. Get the application URL by running these commands:
 #  export POD_NAME=$(kubectl get pods --namespace kafkaui -l "app.kubernetes.io/name=kafkaui,app.kubernetes.io/instance=kafkaui" -o jsonpath="{.items[0].metadata.name}")
 #  echo "Visit http://127.0.0.1:8080 to use your application"
 #  kubectl --namespace kafkaui port-forward $POD_NAME 8080:8080

helm upgrade kafkaui ./kafkaui-0.0.9.tgz \
     --install \
     --atomic \
     --timeout 5m \
     --namespace kafkaui \
     --set image.repository="provectuslabs/kafka-ui" \
     --set image.tag="v0.4.0" \
     --history-max 3 \
     -f kafkaui/values.yaml
#     --values kafkaui/values-env.yaml