apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: tools
  source:
    repoURL: https://github.com/jothep/Infra-dojo-k8s.git
    targetRevision: v0.1
    path: helmCharts/sealed-secrets
    helm:
      releaseName: sealedsecrets
      valueFiles:
        - values.yaml
        - extra-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
