---
- name: Install prerequisite packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes
  become: true

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '0644'

- name: De-armor the GPG key
  command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: true

- name: Add Docker's APT repository
  apt_repository:
    repo: "deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: true

- name: Add user to the 'docker' group for non-root access
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: "Print a reminder message about re-login"
  debug:
  msg:
    - "======================================================================="
    - "Docker installed successfully!"
    - "IMPORTANT: In order for the current user '{{ ansible_user }}' to run docker commands without sudo,"
    - "You must first **log out** of the current SSH session and then **log in** again."
    - "(Log out and log back in for the 'docker' group changes to take effect.)"
    - "========================================================================="